## Quiz 11: Joins

### Madison Ward

For my assignment, I chose the tables "bikeshare_trips" and "bikeshare_stations" from the Austin Bikeshare Data set.

In [24]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

#### 1. Inner Join

Shows only trips with a matching station

In [26]:
%%bigquery --project joins-489323
SELECT
    stations.name AS station_name,
    trips.duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` AS trips
INNER JOIN `bigquery-public-data.austin_bikeshare.bikeshare_stations` AS stations
ON trips.start_station_id = stations.station_id

Query is running:   0%|          |

Downloading:   0%|          |

                          station_name  duration_minutes
0                     10th & Red River               128
1                     10th & Red River                75
2                     10th & Red River                47
3                     10th & Red River               122
4                     Guadalupe & 21st                50
...                                ...               ...
2155754                    Zilker Park                43
2155755                    Zilker Park                43
2155756                    Zilker Park                43
2155757                    Zilker Park                43
2155758  Pfluger Bridge @ W 2nd Street                43

[2155759 rows x 2 columns]

#### 2. Left Join

Shows all trips, even if the sation isn't listed.

In [28]:
%%bigquery --project joins-489323
SELECT
    stations.name AS station_name,
    trips.duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` AS trips
LEFT JOIN `bigquery-public-data.austin_bikeshare.bikeshare_stations` AS stations
ON trips.start_station_id = stations.station_id

Query is running:   0%|          |

Downloading:   0%|          |

                              station_name  duration_minutes
0                         10th & Red River               600
1                         10th & Red River               131
2                         10th & Red River                44
3                         10th & Red River               106
4                         10th & Red River               104
...                                    ...               ...
2271147                        Zilker Park                44
2271148                        Zilker Park                44
2271149                     2nd & Congress                44
2271150                   5th & San Marcos                44
2271151  Capitol Station / Congress & 11th                44

[2271152 rows x 2 columns]

#### 3. Right Join

Shows all stations, even if no trips started there.

In [29]:
%%bigquery --project joins-489323
SELECT
    stations.name AS station_name,
    trips.duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` AS trips
RIGHT JOIN `bigquery-public-data.austin_bikeshare.bikeshare_stations` AS stations
ON trips.start_station_id = stations.station_id

Query is running:   0%|          |

Downloading:   0%|          |

                       station_name  duration_minutes
0                  10th & Red River               267
1                  10th & Red River                75
2                  10th & Red River               181
3        East 11th St. & San Marcos               136
4                 Palmer Auditorium                62
...                             ...               ...
2155761                 Zilker Park                44
2155762                 Zilker Park                44
2155763                 Zilker Park                44
2155764                 Zilker Park                44
2155765                 Zilker Park                44

[2155766 rows x 2 columns]

#### 4. Full Outer Join

Shows all trips and stations, if there is no match, shows "null".

In [30]:
%%bigquery --project joins-489323
SELECT
    trips.start_station_id,
    stations.station_id AS matched_station_id,
    stations.name AS station_name,
    trips.duration_minutes
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips` AS trips
FULL OUTER JOIN `bigquery-public-data.austin_bikeshare.bikeshare_stations` AS stations
ON trips.start_station_id = stations.station_id

Query is running:   0%|          |

Downloading:   0%|          |

,start_station_id,matched_station_id,station_name,duration_minutes
0,4051,4051,10th & Red River,267
1,4051,4051,10th & Red River,37
2,4051,4051,10th & Red River,266
3,4051,4051,10th & Red River,20
4,3635,3635,13th & San Antonio,11
...,...,...,...,...
2271154,2574,2574,Zilker Park,46
2271155,2574,2574,Zilker Park,72
2271156,2574,2574,Zilker Park,35
2271157,2574,2574,Zilker Park,16
2271158,2574,2574,Zilker Park,34